"""Increased the length of the password in the user model, changed the type to text, in order to accommodate the password hash

Revision ID: 7e3ee4722748
Revises: 654ac197a86e
Create Date: 2021-12-19 01:34:08.028920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3ee4722748'
down_revision = '654ac197a86e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['user_email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
