"""users.status has been changed to boolean user.is_admin

Revision ID: c0c19c9eae27
Revises: 7e3ee4722748
Create Date: 2021-12-19 10:11:14.309699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0c19c9eae27'
down_revision = '7e3ee4722748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True, default=False))
    op.create_unique_constraint(None, 'users', ['user_name'])
    op.drop_column('users', 'user_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
